### ISSUE TITLE
Coordinates Map's Corners?

### ISSUE THREAD

**Issue by kochmich** [klightspeed/EliteDangerousRegionMap#2]
You do very great work and research! Thanks a lot!
I've a question to the both basemaps "RegionMap.png" and "Region.Map.svg"" and I hope, you can help me. Think it is easy for you to answer...

I'm seeking the coordinates for the Map's Corners left-down and right-up. So it would be possible to use your maps in other mapping projects... 

Many thanks in advance for your reply.
Cmdr Latenoid

**Comment by klightspeed** [comment]
The bottom-left corner of the map is at the origin point of the Elite Dangerous coordinate system (X=-49985, Z=-24105).
There are then 83 pixels every 4096ly.  Given that both the svg and png are 2048x2048, this puts the top right corner at X=8388608/83-49985 and Z=8388608/83-24105 or approximately X=51082.566 and Z=76962.566

**Comment by kochmich** [comment]
Thank you very much for your quick reply. Your information is a great help to me. In a German E:D Forum we talk a lot about mapping life forms. This is how we found your project, because we need a map base that is as precise as possible. If you want, our thread can be found here: https://elitedangerous.de/forum/index.php?thread/22481-atlas-of-life/

When we draw maps, we of course always name the author of the data. It is common to use the name of the commander. Do you have a commander name? Or should I use your nickname 'klightspeed'? Please let me know your wish.

I have another suggestion for your project that might arouse your interest. Would it be possible to plot the points of the regional boundaries as an Excel document? The results should correspond to the E: D coordinate system.

Greetings from Germany,
Cmdr Latenoid

**Comment by klightspeed** [comment]
My in-game name is CMDR Bravada Cadelanne.

I began investigating the region borders in March last year <https://forums.frontier.co.uk/threads/determining-the-region-of-a-system.537845/page-3#post-8329890>

After tracing the borders, I posted about this in the #developers channel of the EDCD discord in September last year.

As mentioned in the above, at the edges of regions some parts of the game (e.g. the region display when jumping to a system, or the true assignment of codex discoveries) use the actual position of the system, while other parts of the game (e.g. the region displayed on the codex front page or the region codex discoveries are assigned to in the journal) use the "boxel" position of the system (i.e. the bottom left coordinate of the "boxel" the star is in, where e.g. `a` mass-code stars have 10ly boxels, `d` mass-code stars have 80ly boxels, and `h` mass-code stars have 1280ly boxels - see http://disc.thargoid.space/Sector_Naming#The_System_Identifiers for more info on mass-code).

**Comment by klightspeed** [comment]
> I have another suggestion for your project that might arouse your interest. Would it be possible to plot the points of the regional boundaries as an Excel document? The results should correspond to the E: D coordinate system.

As in a 2048x2048 spreadsheet with each cell containing what region that cell is in, and an index formula that can be used to look up a position based on its X and Z coordinates?

**Comment by klightspeed** [comment]
https://drive.google.com/file/d/1FjlHWFm_DKm6q8VhiZRz3xgu8fjGFCtf/view?usp=sharing

**Comment by kochmich** [comment]
Holla! That looks crazy. But I'm not sure if I meant it that way.
Basically I mean a 3-column table based on your map. Or instead of this, a calculation on your data.

E.g.

x / y (z) / value (1 = black, 0 = white)
0/0/0
1/1/0
1/2/1
1/3/0

... i.e. at coord. 1/2 there is 1 black pixel.

Then eliminate the "0" values, so that a relatively small table of coordinates comes out (instead of a table with about 4 million lines).
The coordinates of the bitmap would then have to be shifted to an E: D-coordinate via Excel.

I attach the map from you converted as BW.GIF
![Galaxis Regionen SW (GIF)](https://user-images.githubusercontent.com/44752904/111283992-fb2ca200-863f-11eb-8a18-4777c2b31b68.gif)


.

**Comment by kochmich** [comment]
Note on the Map: I removed the outer ring as it is not relevant to the result, because End of Galaxy and no Stars.

**Comment by kochmich** [comment]
Thanks to your help with the basic coordinates, I was able to make the attached graphic. 
There I compare the distribution of four species and their relationship to regional borders. The left column of the image is based on your card. The right column to that of CMDR Qohen Leth. 
As you can easily see, mapping based on your data is much more precise. So I was able to verify your work and confirm your result. I published this in Frontierforum.

![Nachweis cmdr Cadelanne vs cmdr Leth  cmdr Latenoid  (Kopie)](https://user-images.githubusercontent.com/44752904/111290423-6f6a4400-8646-11eb-8d9e-7a9588011735.jpg)

**Comment by klightspeed** [comment]
If you only care about the borders, and do not need to be pixel-perfect, then here is the SVG of the segment borders (with outer ring removed):
[RegionMap2.svg.txt](https://github.com/klightspeed/EliteDangerousRegionMap/files/6147990/RegionMap2.svg.txt)
If you do need it to be pixel perfect, then here is the SVG of the region borders (each path in the SVG is 1 region):
[RegionMap1.svg.txt](https://github.com/klightspeed/EliteDangerousRegionMap/files/6147999/RegionMap1.svg.txt)
Coordinates scaled and offset to E:D coordinates:
[RegionMap1a.svg.txt](https://github.com/klightspeed/EliteDangerousRegionMap/files/6148107/RegionMap1a.svg.txt)

**Comment by kochmich** [comment]
Thanks a lot, you are very fast! And thank you for taking the time.
I need a file like the third one.

I just plotted it and got an interesting result. The regions do not look like what we are used to. 
See picture 1.

I then swapped columns A and B. 
See picture 2.

And then I turned it -90 degrees. Now the galaxy apears like we are used, but the labels are of course somewhere else.
See picture 3.

As you can see, your coordinates have been swirled around.
It is interesting to see that the point density decreases towards the main coordinates.

It's probably very complicated, but do you think you can tweak it?



![Step 1](https://user-images.githubusercontent.com/44752904/111301549-a47c9380-8652-11eb-94e1-3d7c38dc55f5.jpg)

![Step 2](https://user-images.githubusercontent.com/44752904/111301566-a9414780-8652-11eb-900a-340a3a56270f.jpg)

![Step 3](https://user-images.githubusercontent.com/44752904/111301577-aba3a180-8652-11eb-8065-cf179a1029f5.jpg)

**Comment by klightspeed** [comment]
Sorry, I forgot that the Y coordinates are flipped when I scaled and offset them.
The point density reduces near the axes due to the points describing the ends of line segments.
Here is a modified one where each line segment is the same length, and the Y coordinates are correctly flipped:
[RegionMap1b.svg.txt](https://github.com/klightspeed/EliteDangerousRegionMap/files/6148786/RegionMap1b.svg.txt)

**Comment by klightspeed** [comment]
Sorry, just realized that there is an error in the above.  One moment.

Edit: Zero-length segments removed:
[RegionMap1b.svg.txt](https://github.com/klightspeed/EliteDangerousRegionMap/files/6148879/RegionMap1b.svg.txt)

**Comment by kochmich** [comment]
You made it :-) !

Here's the result - thanks a lot. 

You are a very great programmer!


![New Basemap](https://user-images.githubusercontent.com/44752904/111308030-7ac76a80-865a-11eb-98a5-b2450674c20d.jpg)
