### ISSUE TITLE
translations from [b]{x,y,z} to in-game coords

### ISSUE THREAD

**Issue by jnorthrup** [klightspeed/EliteDangerousRegionMap#3]
I recently discovered the id64 and your code to decode the coordinate features.  there are a few descriptions online but code is pretty convenient.

what is the conversion from id64 to in-game plotter/map coordinates from the id64 x,y,z and boxes?  how do we convert the integral values to floatin points?

**Comment by klightspeed** [comment]
Please refer to https://disc.thargoid.space/ID64 for how the id64 (`SystemAddress`) is structured.

Converting from id64 to in-game coordinates is going to get you at best within a 10x10x10ly boxel for `a` masscode systems, within a 80x80x80ly boxel for `d` masscode systems, or within a 1280x1280x1280ly boxel for `h` masscode systems, so it's not possible to directly convert an id64 to coordinates.

It's also not possible to convert coordinates to an id64 without both the system masscode and the sequence number of the system within the boxel.

**Comment by jnorthrup** [comment]
so if we are building an octree of our own these x,y,z are the right scale and placement if not the precise point then?

**Comment by jnorthrup** [comment]
for the purposes of plotting routes, even if heavy masscode systems appear for routes they really aren't useful for it seems like the xyz of the id64 is a decent index.  I am assuming high mass code systems are less numerous than the low masscodes and the occurence of these in a search for an unrelated route isn't going to numerically overpower the relevant paths

**Comment by klightspeed** [comment]
If you are getting systems for route plotting from the EDSM systems dump or Spansh galaxy dump, then you should be able to use the coordinates for the systems from those dumps.

The normal way of getting systems from the journal (`FSDJump` / `Location` / `NavRoute`) should also all currently have coordinates associated with every system the game writes to the journal or `NavRoute.json`.
